using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;
using PSXRacing.LifeSim;

namespace PSXRacing
{
    /// <summary>
    /// THE CREDITS PAGE the pause menu opens (Charlotte refinement WP-02, plan
    /// critic C17): the credit and licence lines the map and terrain data owe,
    /// in full. The in-race HUD only has room for a seven-second
    /// "MAP DATA (C) OPENSTREETMAP CONTRIBUTORS", and the terrain's credit
    /// (the AWS Terrain Tiles / USGS line) had no place in the game at all.
    ///
    /// The text is the build's own edition's page (Resources/psx_credits.txt
    /// for ALL, psx_credits_main.txt, psx_credits_city.txt), generated with
    /// LICENSES.txt (published beside index.html, the edition's again) and
    /// the front pages' one-line credit (<see cref="Line(EditionKind)"/>)
    /// from tools/city/SOURCES.md by tools/city/credits.mjs, so the page, the
    /// file on Pages, the door and the attribution inside the data all say
    /// the same thing. Plain text, WRAPPED to the column (owner rule: no text
    /// may clip).
    ///
    /// Opened over the pause menu like the debug bench and closed the same
    /// way: BACK, Escape, B / Circle or START, and the pause menu ignores the
    /// frame this page closed on (<see cref="ClosedFrame"/>).
    /// </summary>
    public class CreditsPanel : MonoBehaviour
    {
        public System.Action onClosed;
        public bool IsOpen { get; private set; }
        /// <summary>The frame the page last closed on; see
        /// DebugCarPanel.ClosedFrame for why the pause menu needs it.</summary>
        public int ClosedFrame { get; private set; } = -1;

        // PER EDITION (tools/city/SOURCES.md, "THE EDITIONS"): MAIN credits
        // the stages' data and CITY Charlotte's, because each build carries
        // only its own; ALL credits both. All of these are generated by
        // tools/city/credits.mjs from SOURCES.md's Credits table - never
        // written here - and are a few hundred bytes, so every build carries
        // all of them and asks for its own.
        const string ResourceName = "psx_credits";           // ALL's page
        const string MainResource = "psx_credits_main";
        const string CityResource = "psx_credits_city";
        /// <summary>One "EDITION: line" row per edition: the short credit a
        /// front page prints (<see cref="Line(EditionKind)"/>).</summary>
        const string LineResource = "psx_credits_line";
        /// <summary>What the page says if the generated text is missing: the
        /// one credit ODbL cannot do without.</summary>
        public const string Fallback = "MAP, TERRAIN AND MODEL CREDITS\n\nRoad network data (c) OpenStreetMap contributors, ODbL 1.0";
        /// <summary>The front-page line if the generated one is missing: the
        /// same one credit.</summary>
        public const string LineFallback = "Map data (c) OpenStreetMap contributors, ODbL.";

        Canvas canvas;
        readonly List<MenuNavWatch> stoodDown = new List<MenuNavWatch>();

        /// <summary>This build's page: the generated credits of the edition it
        /// is (<see cref="Edition.Current"/>), or the fallback.</summary>
        public static string Text() => Text(Edition.Current);

        /// <summary>The CREDITS page of <paramref name="edition"/>. A missing
        /// edition page falls back to ALL's (more credits than the build owes,
        /// never fewer), and a missing ALL to the ODbL line.</summary>
        public static string Text(EditionKind edition)
        {
            string s = null;
            if (edition == EditionKind.Main) s = Load(MainResource);
            else if (edition == EditionKind.City) s = Load(CityResource);
            if (string.IsNullOrEmpty(s)) s = Load(ResourceName);
            return string.IsNullOrEmpty(s) ? Fallback : s.Replace("\r\n", "\n").TrimEnd();
        }

        /// <summary>This build's one-line credit.</summary>
        public static string Line() => Line(Edition.Current);

        /// <summary>
        /// The one-line data credit a front page prints for
        /// <paramref name="edition"/> (the CITY front page prints CITY's): its
        /// row of Resources/psx_credits_line.txt, made from the "short" column
        /// of SOURCES.md's Credits table. ALL's row if the edition has none,
        /// the ODbL line if the file is missing.
        /// </summary>
        public static string Line(EditionKind edition)
        {
            string s = Load(LineResource);
            if (string.IsNullOrEmpty(s)) return LineFallback;
            string want = Edition.Name(edition) + ":", all = Edition.Name(EditionKind.All) + ":";
            string mine = null, any = null;
            foreach (var raw in s.Split('\n'))
            {
                string l = raw.Trim();
                if (l.Length == 0 || l[0] == '#') continue;
                if (mine == null && l.StartsWith(want, System.StringComparison.Ordinal)) mine = l.Substring(want.Length).Trim();
                else if (any == null && l.StartsWith(all, System.StringComparison.Ordinal)) any = l.Substring(all.Length).Trim();
            }
            if (!string.IsNullOrEmpty(mine)) return mine;
            return string.IsNullOrEmpty(any) ? LineFallback : any;
        }

        static string Load(string name)
        {
            var ta = Resources.Load<TextAsset>(name);
            if (ta == null) return null;
            string s = ta.text;
            Resources.UnloadAsset(ta);
            return s;
        }

        public void Open()
        {
            if (IsOpen) return;
            IsOpen = true;
            Cursor.lockState = CursorLockMode.None;
            Cursor.visible = true;
            MenuKit.EnsureEventSystem();
            canvas = MenuKit.Canvas(transform, "CreditsCanvas", 210);   // over the pause menu's 200
            MenuKit.Panel(canvas.transform, "Backdrop", new Color(0.08f, 0.08f, 0.08f, 0.94f));
            MenuKit.GridBackdrop(canvas.transform);
            // The pause menu's nav watch would pull the cursor back onto its
            // own rows; it stands down while this page is up.
            stoodDown.Clear();
            foreach (var w in FindObjectsByType<MenuNavWatch>(FindObjectsInactive.Exclude))
                if (w != null && w.enabled) { w.enabled = false; stoodDown.Add(w); }
            var back = Build(canvas.transform);
            MenuNav.Select(back);
        }

        public void Close()
        {
            if (!IsOpen) return;
            IsOpen = false;
            ClosedFrame = Time.frameCount;
            foreach (var w in stoodDown) if (w != null) w.enabled = true;
            stoodDown.Clear();
            // DestroyImmediate outside play mode: the preview tool opens the
            // page in the editor.
            if (canvas != null) { if (Application.isPlaying) Destroy(canvas.gameObject); else DestroyImmediate(canvas.gameObject); }
            canvas = null;
            onClosed?.Invoke();
        }

        void OnDisable() { if (IsOpen) Close(); }

        void Update()
        {
            if (!IsOpen) return;
            var kb = UnityEngine.InputSystem.Keyboard.current;
            var pad = UnityEngine.InputSystem.Gamepad.current;
            if ((kb != null && kb.escapeKey.wasPressedThisFrame) ||
                (pad != null && (pad.buttonEast.wasPressedThisFrame || pad.startButton.wasPressedThisFrame)))
                Close();
        }

        /// <summary>
        /// Lay the page out on <paramref name="parent"/> (a MenuKit canvas):
        /// the title, the text wrapped to a column that fits the canvas at any
        /// aspect, and BACK under it. Returns the BACK button. Public for the
        /// preview tool, which lays it out without play mode.
        /// </summary>
        public Button Build(Transform parent)
        {
            var top = new Vector2(0.5f, 1f);
            var title = MenuKit.Label(parent, "CREDITS", 34, top, new Vector2(0f, -56f),
                                      TextAnchor.MiddleCenter, MenuKit.Accent, 600f, 50f, bold: true);
            // The column: never wider than the canvas less a margin each side,
            // never wider than a comfortable reading width.
            float colW = Mathf.Min(900f, MenuKit.HalfWidth * 2f - 96f);
            float y = -104f;
            string text = Text();
            // Left-aligned text: x is the column's LEFT edge (MenuKit pivots a
            // label on its alignment), so the column is centred by starting it
            // half its width left of the middle.
            var one = MenuKit.Para(parent, text, 20, top, new Vector2(-colW * 0.5f, y), out float used,
                                   TextAnchor.UpperLeft, Color.white, colW);
            // TWO COLUMNS where one runs past BACK's room (WP-04: five credits
            // since the 3DEP ground and the county and USGS water, and a phone's
            // canvas is 560 units tall, so BACK stood off the bottom of it). The
            // paragraphs are split where the taller column is shortest; the
            // type stays at 20 (the owner's floor).
            float room = MenuKit.DesignHeight + y - 18f - 44f - 16f;
            if (used > room)
            {
                var paras = text.Split(new[] { "\n\n" }, System.StringSplitOptions.None);
                float wide = Mathf.Min(1500f, MenuKit.HalfWidth * 2f - 96f), gap = 40f, half = (wide - gap) * 0.5f;
                float Measure(string s)
                {
                    var t = MenuKit.Para(parent, s, 20, top, Vector2.zero, out float h, TextAnchor.UpperLeft, Color.white, half);
                    Kill(t.gameObject);
                    return h;
                }
                int bestK = -1; float bestH = used;
                for (int k = 1; k < paras.Length; k++)
                {
                    float h = Mathf.Max(Measure(string.Join("\n\n", paras, 0, k)), Measure(string.Join("\n\n", paras, k, paras.Length - k)));
                    if (h < bestH) { bestH = h; bestK = k; }
                }
                if (bestK > 0)
                {
                    Kill(one.gameObject);
                    MenuKit.Para(parent, string.Join("\n\n", paras, 0, bestK), 20, top, new Vector2(-wide * 0.5f, y), out float hL,
                                 TextAnchor.UpperLeft, Color.white, half);
                    MenuKit.Para(parent, string.Join("\n\n", paras, bestK, paras.Length - bestK), 20, top, new Vector2(-wide * 0.5f + half + gap, y), out float hR,
                                 TextAnchor.UpperLeft, Color.white, half);
                    used = Mathf.Max(hL, hR);
                }
            }
            y -= used + 18f;
            var back = MenuKit.Button(parent, "BACK", top, new Vector2(0f, y - 22f), new Vector2(260f, 44f), Close, 22);
            back.navigation = new Navigation { mode = Navigation.Mode.None };
            return back;
        }

        /// <summary>Destroy a laid-out object in play mode or in the preview tool.</summary>
        static void Kill(GameObject go)
        {
            if (Application.isPlaying) { go.SetActive(false); Destroy(go); } else DestroyImmediate(go);
        }
    }
}
